
[build]
rustflags = [
  "-C", "force-frame-pointers=yes",
  "-C", "llvm-args=--inline-threshold=0",        
  "-C", "codegen-units=1"         
]

[alias]
prof = "build --profile profiling --features alloc-prof"
prof-run = "run --profile profiling --features alloc-prof"
prof-test = "test --profile profiling --features alloc-prof"

